version: "3"

services:
  todo:
    image: iamharryb/todo:test
    restart: always
    container_name: todo
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: todo-mongo
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    restart: always

volumes:
  dbdata: