version: 2
jobs:
   build:
      docker:
         - image: circleci/openjdk:11-jdk-stretch
      steps:
         - checkout

         - restore_cache:
            key: todo-{{ checksum "pom.xml" }}

         - run: mvn dependency:go-offline

         - save_cache:
            paths:
               - ~/.m2
            key: todo-{{ checksum "pom.xml" }}

         - run: mvn package

         - store_test_results:
            path: target/surefire-reports